# Generated by Django 5.1 on 2024-08-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_remove_tool_tokenmqtt_tool_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='mqtttoken',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
