# Generated by Django 5.1 on 2024-08-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokenkey',
            field=models.CharField(default='GAADA', editable=False, max_length=7, unique=True),
        ),
    ]
