# Generated by Django 5.1 on 2024-08-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_tokenkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tokenkey',
            field=models.CharField(default='GAADA', max_length=7, unique=True),
        ),
    ]
