# Generated by Django 5.1 on 2024-08-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tokenkey',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
