# Generated by Django 5.1 on 2024-08-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_tokenkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tokenkey',
            new_name='mqtttoken',
        ),
    ]
