# Generated by Django 5.1 on 2024-08-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
