# Generated by Django 5.1 on 2024-08-26 01:04

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_profile_pic.png', null=True, upload_to=account.models.UserDirectoryPath),
        ),
    ]
